Update S3 bucket.yml

diff --git a/.github/workflows/S3 bucket.yml b/.github/workflows/S3 bucket.yml
--- a/.github/workflows/S3 bucket.yml
+++ b/.github/workflows/S3 bucket.yml
@@ -113,7 +113,8 @@ jobs:
           SERVICE_NAME="SI-service"
           TASK_DEFINITION_NAME="SI-task"
 
-          SERVICE_EXISTS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].status' --output text --region us-east-1 2>/dev/null || echo "MISSING")
+          # Check if the service already exists
+          SERVICE_EXISTS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].serviceName' --output text --region us-east-1 2>/dev/null || echo "MISSING")
 
           if [ "$SERVICE_EXISTS" == "MISSING" ]; then
             echo "Service $SERVICE_NAME does not exist. Creating service..."
