Update S3 bucket.yml

diff --git a/.github/workflows/S3 bucket.yml b/.github/workflows/S3 bucket.yml
--- a/.github/workflows/S3 bucket.yml
+++ b/.github/workflows/S3 bucket.yml
@@ -215,17 +215,17 @@ jobs:
           SERVICE_NAME=si-service
           TASK_DEFINITION_NAME=si-task
       
-          # Check if the service already exists
-          SERVICE_EXISTS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].status' --output text --region us-east-1 2>/dev/null || echo "MISSING")
-
+           SERVICE_EXISTS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].status' --output text --region us-east-1 2>/dev/null || echo "MISSING")
+  
             if [ "$SERVICE_EXISTS" == "MISSING" ]; then
-              echo "Service $SERVICE_NAME does not exist. Creating service..."
+              # Create the service if it doesn't exist
               aws ecs create-service \
                 --cluster $CLUSTER_NAME \
                 --service-name $SERVICE_NAME \
                 --task-definition $TASK_DEFINITION_NAME \
                 --desired-count 1 \
                 --launch-type FARGATE \
+
                 --network-configuration "awsvpcConfiguration={subnets=[${{ env.SUBNETS }}],securityGroups=[${{ env.SECURITY_GROUP_ID }}],assignPublicIp=ENABLED}" \
                 --region us-east-1
             else
